// Generated by tauri-specta. Do not edit.
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Connect to a profile, replacing any current session. */
	connect: (profileId: string) => __TAURI_INVOKE<ConnectOutcome>("connect", { profileId }),
	disconnect: () => __TAURI_INVOKE<null>("disconnect"),
	/**  The live session, if any (lets the UI recover after a webview reload). */
	sessionInfo: () => __TAURI_INVOKE<{
	profileId: string,
	host: string,
	user: string,
	home: string,
	isRoot: boolean,
	hasSudo: boolean,
} | null>("session_info"),
	/**  Ask the monitor to retry right away instead of waiting out the backoff. */
	reconnectNow: () => __TAURI_INVOKE<void>("reconnect_now"),
	sudoStatus: () => __TAURI_INVOKE<SudoStatus>("sudo_status"),
	/**  Verify the sudo password and cache it for the session (15 minutes). */
	sudoAuthenticate: (password: string) => __TAURI_INVOKE<null>("sudo_authenticate", { password }),
	sudoForget: () => __TAURI_INVOKE<void>("sudo_forget"),
	knownHostsList: () => __TAURI_INVOKE<KnownHost[]>("known_hosts_list"),
	/**
	 *  Trust a host key shown in the fingerprint prompt. `replace` drops the
	 *  previously trusted keys for that host (the "key changed" path).
	 */
	knownHostTrust: (host: string, port: number, key: string, replace: boolean) => __TAURI_INVOKE<null>("known_host_trust", { host, port, key, replace }),
	knownHostForget: (host: string, port: number) => __TAURI_INVOKE<null>("known_host_forget", { host, port }),
	profilesList: () => __TAURI_INVOKE<ProfileView[]>("profiles_list"),
	profileSave: (input: ProfileInput) => __TAURI_INVOKE<ProfileView>("profile_save", { input }),
	/**  Delete a profile together with all of its data and secrets. */
	profileDelete: (profileId: string) => __TAURI_INVOKE<null>("profile_delete", { profileId }),
	profileSetDefault: (profileId: string | null) => __TAURI_INVOKE<null>("profile_set_default", { profileId }),
	/**  Validate a picked key file; a `.pub` resolves to its private sibling. */
	profileResolveKey: (path: string) => __TAURI_INVOKE<string>("profile_resolve_key", { path }),
	/**  Folder the key picker should open in. */
	defaultKeyDir: () => __TAURI_INVOKE<string | null>("default_key_dir"),
	/**
	 *  One per-profile document as JSON text (`null` when nothing is stored).
	 *  Documents travel as text because their shape belongs to the feature that
	 *  owns them; the frontend wraps this in a typed accessor per [`DataKey`].
	 */
	profileDataGet: (profileId: string, key: DataKey) => __TAURI_INVOKE<string>("profile_data_get", { profileId, key }),
	profileDataSet: (profileId: string, key: DataKey, json: string) => __TAURI_INVOKE<null>("profile_data_set", { profileId, key, json }),
	settingsGet: () => __TAURI_INVOKE<AppSettings>("settings_get"),
	settingsSet: (settings: AppSettings) => __TAURI_INVOKE<null>("settings_set", { settings }),
	defaultDownloadDir: () => __TAURI_INVOKE<string>("default_download_dir"),
	/**
	 *  Problems found while loading local files (e.g. a corrupt store that was
	 *  set aside). Returned once.
	 */
	startupNotices: () => __TAURI_INVOKE<AppError[]>("startup_notices"),
	/**
	 *  Store a secret in the OS keyring. `profile_id = null` is the global scope.
	 *  Secrets are write-only for the UI: there is no command that reads one back.
	 */
	secretSet: (profileId: string | null, name: string, value: string) => __TAURI_INVOKE<null>("secret_set", { profileId, name, value }),
	secretExists: (profileId: string | null, name: string) => __TAURI_INVOKE<boolean>("secret_exists", { profileId, name }),
	/**  Clear one secret, or every secret under a `prefix/`. */
	secretClear: (profileId: string | null, name: string) => __TAURI_INVOKE<null>("secret_clear", { profileId, name }),
	/**
	 *  Write text to a local file the user picked in a save dialog
	 *  (log downloads, query exports).
	 */
	saveTextFile: (path: string, content: string) => __TAURI_INVOKE<null>("save_text_file", { path, content }),
	jobCancel: (jobId: string) => __TAURI_INVOKE<void>("job_cancel", { jobId }),
	depsCheck: (tools: Tool[]) => __TAURI_INVOKE<DepsReport>("deps_check", { tools }),
	/**  Install a tool as a streamed job; returns the job id. */
	depsInstall: (tool: Tool) => __TAURI_INVOKE<string>("deps_install", { tool }),
};

/** Events */
export const events = {
	connectionStatus: makeEvent<ConnectionStatus>("connection-status"),
	jobDone: makeEvent<JobDone>("job-done"),
	jobOutput: makeEvent<JobOutput>("job-output"),
	jobStarted: makeEvent<JobStarted>("job-started"),
};

/* Types */
export type AppError = {
	code: ErrorCode,
	details: string | null,
};

export type AppSettings = {
	theme: Theme,
	sidebarCollapsed: boolean,
	/**  Tab ids pinned to the Favourites section. */
	favourites: string[],
	/**  Tab id → colour tag name. */
	tabColors: { [key in string]: string },
	terminal: TerminalPrefs,
	/**  Default local folder for downloads; `None` means the OS Downloads folder. */
	downloadDir: string | null,
	pangolin: PangolinSettings,
};

export type AuthType = "password" | "key";

export type ConnectOutcome = { status: "connected"; session: SessionInfo } | 
/**  The server's host key needs a decision before connecting. */
{ status: "hostKey"; issue: HostKeyIssue };

export type ConnectionStatus = {
	profileId: string,
	state: LinkState,
	attempt: number,
	error: AppError | null,
};

export type DataKey = "runbooks" | "savedCommands" | "sftpBookmarks" | "backupTemplates" | "resticRepos" | "alertThresholds" | "dbConnections" | "nginxTargets" | "logAnalysisProfiles" | "logSources" | "crowdsecConfig" | "composeStacks" | "workspaceLayout";

export type DepsReport = {
	packageManager: PackageManager | null,
	tools: ToolStatus[],
};

export type ErrorCode = "NOT_CONNECTED" | "CONNECTION_FAILED" | "CONNECTION_LOST" | "AUTH_FAILED" | "HOST_KEY_UNKNOWN" | "HOST_KEY_CHANGED" | "KEY_FILE_INVALID" | "KEY_PASSPHRASE_REQUIRED" | "KEY_PASSPHRASE_WRONG" | "TIMEOUT" | "CANCELLED" | "SUDO_PASSWORD_REQUIRED" | "SUDO_PASSWORD_EXPIRED" | "SUDO_PASSWORD_WRONG" | "SUDO_LOCKED" | "SUDO_UNAVAILABLE" | "PERMISSION_DENIED" | "NOT_FOUND" | "ALREADY_EXISTS" | "INVALID_INPUT" | "COMMAND_FAILED" | "PARSE_FAILED" | "DEPENDENCY_MISSING" | "UNSUPPORTED" | "IO" | "STORE_CORRUPT" | "KEYRING" | "SFTP" | "TRANSFER_FAILED" | "FILE_TOO_LARGE" | "BINARY_FILE" | "DATABASE" | "DB_NOT_CONNECTED" | "HTTP" | "PANGOLIN_NOT_CONFIGURED" | "PANGOLIN_UNAUTHORIZED" | "CONFIG_TEST_FAILED" | "INTERNAL";

/**  Why a server's host key was not accepted, with what the user needs to decide. */
export type HostKeyIssue = {
	host: string,
	port: number,
	keyType: string,
	fingerprint: string,
	/**  Fingerprints currently trusted for this host; empty on first contact. */
	knownFingerprints: string[],
	/**  The offered key in OpenSSH format, passed back to trust it. */
	key: string,
};

export type JobDone = {
	jobId: string,
	exitCode: number | null,
	error: AppError | null,
	cancelled: boolean,
};

export type JobOutput = {
	jobId: string,
	stream: JobStream,
	chunk: string,
};

export type JobStarted = {
	jobId: string,
	/**  Short label, e.g. "Compose up · blog". */
	title: string,
	/**  Full command or description. */
	detail: string,
	/**  Whether the job belongs in the Running Jobs panel. */
	visible: boolean,
	startedAt: number,
};

export type JobStream = "stdout" | "stderr";

export type KnownHost = {
	host: string,
	port: number,
	keyType: string,
	fingerprint: string,
};

export type LinkState = "online" | "offline" | "reconnecting";

export type PackageManager = "apt" | "dnf" | "yum" | "apk" | "pacman" | "zypper";

export type PangolinSettings = {
	apiUrl: string,
	orgId: string,
};

export type Profile = {
	id: string,
	label: string,
	host: string,
	port: number,
	username: string,
	authType: AuthType,
	keyPath: string | null,
	isDefault: boolean,
};

export type ProfileInput = {
	/**  `None` creates a new profile. */
	id: string | null,
	label: string,
	host: string,
	port: number,
	username: string,
	authType: AuthType,
	keyPath: string | null,
	/**  `None` keeps whatever is stored; `Some` replaces it. */
	password: string | null,
	passphrase: string | null,
	/**  Explicitly forget the stored password / passphrase. */
	clearSecrets: boolean,
};

export type ProfileView = {
	profile: Profile,
	hasPassword: boolean,
	hasPassphrase: boolean,
};

export type SessionInfo = {
	profileId: string,
	host: string,
	user: string,
	home: string,
	isRoot: boolean,
	hasSudo: boolean,
};

export type SudoMode = "root" | "passwordless" | "password" | "unavailable";

export type SudoStatus = {
	mode: SudoMode,
	/**  Elevated commands can run right now without prompting. */
	ready: boolean,
};

export type TerminalPrefs = {
	fontFamily: string,
	fontSize: number,
	/**  Name of a built-in terminal colour scheme. */
	theme: string,
	copyOnSelect: boolean,
	rightClickPaste: boolean,
	scrollback: number,
};

export type Theme = "dark" | "light" | "system";

export type Tool = "systemd" | "cron" | "docker" | "mtr" | "traceroute" | "netcat" | "dig" | "curl" | "ping" | "restic" | "rclone" | "nginx" | "certbot" | "certbotNginx" | "certbotDnsCloudflare" | "certbotDnsDigitalocean" | "certbotDnsRoute53" | "ufw" | "iptables" | "crowdsec" | "crowdsecFirewallBouncer" | "mysqlClient" | "postgresClient" | "parted" | "growpart" | "lsblk" | "ss" | "zip";

export type ToolStatus = {
	tool: Tool,
	label: string,
	installed: boolean,
	/**  False for things Jarvis cannot install (e.g. systemd). */
	installable: boolean,
	/**  Command the user can run by hand; `None` without a known package manager. */
	manualCommand: string | null,
	docsUrl: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

