// Generates docs/ipc-reference.md from the generated bindings, the command
// list in lib.rs (for grouping by backend module) and the error messages.
//
//   pnpm docs:ipc

import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const read = (/** @type {string} */ path) => readFileSync(new URL(path, root), 'utf8').replace(/\r\n/g, '\n');

const bindings = read('src/lib/ipc/bindings.ts');
const lib = read('src-tauri/src/lib.rs');
const errors = read('src/lib/ipc/errors.ts');

const between = (/** @type {string} */ text, /** @type {string} */ from, /** @type {string} */ to) =>
	text.slice(text.indexOf(from), text.indexOf(to, text.indexOf(from)));
const cell = (/** @type {string} */ text) => text.replace(/\s+/g, ' ').trim().replace(/\|/g, '\\|');
const code = (/** @type {string} */ text) => (text ? `\`${cell(text)}\`` : '');

// command name (snake_case) → { name, args, returns, doc }
const commands = new Map();
const entry =
	/(?:\/\*\*((?:(?!\*\/)[\s\S])*)\*\/\s*)?(\w+): \((.*?)\) => __TAURI_INVOKE<([\s\S]*?)>\("(\w+)"/g;
for (const m of between(bindings, 'export const commands', 'export const events').matchAll(entry)) {
	const doc = (m[1] ?? '').replace(/^\s*\*/gm, '');
	commands.set(m[5], { name: m[2], args: m[3], returns: m[4], doc });
}

// Rust module path → command names, in registration order.
const modules = new Map();
for (const m of between(lib, 'collect_commands![', '])').matchAll(/^\s+([\w:]+)::(\w+),$/gm)) {
	modules.set(m[1], [...(modules.get(m[1]) ?? []), m[2]]);
}

const out = [
	'# IPC reference',
	'',
	`Generated by \`pnpm docs:ipc\` from \`src/lib/ipc/bindings.ts\`. Do not edit by hand.`,
	'',
	'Every command is a `#[tauri::command]` in `src-tauri/src/<module>.rs` and is called from the frontend as',
	'`api.<name>(…)`. A command either resolves with its result or rejects with an `AppError`',
	'(`{ code, details }`, see [Error codes](#error-codes)). Type names refer to `src/lib/ipc/bindings.ts`.',
	''
];

for (const [module, names] of modules) {
	out.push(
		`## \`${module.replace(/::/g, '/')}\``,
		'',
		'| Command | Arguments | Returns | Notes |',
		'| --- | --- | --- | --- |'
	);
	for (const name of names) {
		const c = commands.get(name);
		if (!c)
			throw new Error(`${name} is registered in lib.rs but missing from the bindings; run pnpm bindings`);
		out.push(`| \`${c.name}\` | ${code(c.args)} | ${code(c.returns)} | ${cell(c.doc)} |`);
	}
	out.push('');
}

out.push('## Events', '', 'Emitted by the backend; subscribe with `events.<name>.listen(…)`.', '');
out.push('| Event | Wire name | Payload |', '| --- | --- | --- |');
for (const m of between(bindings, 'export const events', '/* Types */').matchAll(
	/(\w+): makeEvent<(\w+)>\("([\w-]+)"\)/g
)) {
	out.push(`| \`${m[1]}\` | \`${m[3]}\` | \`${m[2]}\` |`);
}

out.push(
	'',
	'## Error codes',
	'',
	'The message is what the user sees; `details` is appended when present.',
	''
);
out.push('| Code | Message |', '| --- | --- |');
for (const m of between(errors, 'const MESSAGES', '};').matchAll(/^\t(\w+):\s*'(.*)',?$/gm)) {
	out.push(`| \`${m[1]}\` | ${cell(m[2])} |`);
}

const documented = [...modules.values()].flat().length;
if (documented !== commands.size)
	throw new Error(`lib.rs registers ${documented} commands, bindings have ${commands.size}`);

writeFileSync(new URL('docs/ipc-reference.md', root), out.join('\n') + '\n');
console.log(`docs/ipc-reference.md: ${documented} commands in ${modules.size} modules`);
