//! Jarvis Server Manager backend.
//!
//! One module per domain. Commands take validated arguments and return parsed,
//! typed data; the frontend never builds shell strings.

pub mod connection;
pub mod db;
pub mod deps;
pub mod error;
pub mod jobs;
#[cfg(test)]
mod live_tests;
pub mod local;
pub mod sftp;
pub mod shell;
pub mod ssh;
pub mod state;
pub mod store;
pub mod sudo;
pub mod terminal;
pub mod text;

use tauri::menu::{Menu, MenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{Manager, WindowEvent};
use tauri_specta::{collect_commands, collect_events, Builder, ErrorHandlingMode};

use state::AppState;

fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .error_handling(ErrorHandlingMode::Throw)
        .dangerously_cast_bigints_to_number()
        .disable_serde_phases()
        .commands(collect_commands![
            connection::connect,
            connection::disconnect,
            connection::session_info,
            connection::reconnect_now,
            connection::sudo_status,
            connection::sudo_authenticate,
            connection::sudo_forget,
            connection::known_hosts_list,
            connection::known_host_trust,
            connection::known_host_forget,
            local::profiles_list,
            local::profile_save,
            local::profile_delete,
            local::profile_set_default,
            local::profile_resolve_key,
            local::default_key_dir,
            local::profile_data_get,
            local::profile_data_set,
            local::settings_get,
            local::settings_set,
            local::default_download_dir,
            local::startup_notices,
            local::secret_set,
            local::secret_exists,
            local::secret_clear,
            local::save_text_file,
            jobs::job_cancel,
            deps::deps_check,
            deps::deps_install,
        ])
        .events(collect_events![
            connection::ConnectionStatus,
            jobs::JobStarted,
            jobs::JobOutput,
            jobs::JobDone,
        ])
        .typ::<error::ErrorCode>()
}

/// Write the TypeScript bindings. Run by `cargo test export_bindings` and on
/// every debug start, so the frontend types always match the backend.
pub fn export_bindings() {
    // Walking the full type graph recurses deeply; give it its own roomy stack.
    let export = || {
        specta_builder()
            .export(
                specta_typescript::Typescript::default()
                    .header("// Generated by tauri-specta. Do not edit.\n/* eslint-disable */"),
                concat!(env!("CARGO_MANIFEST_DIR"), "/../src/lib/ipc/bindings.ts"),
            )
            .expect("failed to export TypeScript bindings");
    };
    std::thread::Builder::new()
        .stack_size(64 * 1024 * 1024)
        .spawn(export)
        .expect("failed to start binding export")
        .join()
        .expect("binding export panicked");
}

fn show_main_window(app: &tauri::AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.unminimize();
        let _ = window.show();
        let _ = window.set_focus();
    }
}

fn toggle_main_window(app: &tauri::AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        if window.is_visible().unwrap_or(false) && !window.is_minimized().unwrap_or(false) {
            let _ = window.hide();
        } else {
            show_main_window(app);
        }
    }
}

fn build_tray(app: &tauri::App) -> tauri::Result<()> {
    let show = MenuItem::with_id(app, "show", "Show", true, None::<&str>)?;
    let quit = MenuItem::with_id(app, "quit", "Quit", true, None::<&str>)?;
    let menu = Menu::with_items(app, &[&show, &quit])?;
    let mut tray = TrayIconBuilder::with_id("main")
        .tooltip("Jarvis Server Manager")
        .menu(&menu)
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| match event.id().as_ref() {
            "show" => show_main_window(app),
            "quit" => app.exit(0),
            _ => {}
        })
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            } = event
            {
                toggle_main_window(tray.app_handle());
            }
        });
    if let Some(icon) = app.default_window_icon() {
        tray = tray.icon(icon.clone());
    }
    tray.build(app)?;
    Ok(())
}

pub fn run() {
    // Some GPU/driver combinations show a blank WebKitGTK window with the
    // DMABUF renderer; the SHM path is slower but always works.
    #[cfg(target_os = "linux")]
    if std::env::var_os("WEBKIT_DMABUF_RENDERER_FORCE_SHM").is_none() {
        std::env::set_var("WEBKIT_DMABUF_RENDERER_FORCE_SHM", "1");
    }

    let _ = rustls::crypto::ring::default_provider().install_default();

    let builder = specta_builder();
    #[cfg(debug_assertions)]
    export_bindings();

    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            show_main_window(app);
        }))
        .plugin(tauri_plugin_window_state::Builder::default().build())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let config_dir = app.path().app_config_dir()?;
            std::fs::create_dir_all(&config_dir)?;
            app.manage(AppState::new(config_dir));
            build_tray(app)?;
            Ok(())
        })
        .on_window_event(|window, event| {
            // Closing the window keeps the app (and its sessions) alive in the tray.
            if let WindowEvent::CloseRequested { api, .. } = event {
                if window.label() == "main" {
                    api.prevent_close();
                    let _ = window.hide();
                }
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running Jarvis Server Manager");
}

#[cfg(test)]
mod tests {
    #[test]
    fn export_bindings() {
        super::export_bindings();
    }
}
